### ISSUE TITLE
Migrate to ember-template-lint organization?

### ISSUE THREAD

**Issue by rwjblue** [ember-template-lint/eslint-plugin-hbs#26]
I was wondering if you would be interested in moving this repo into the relatively newly formed `ember-template-lint` organization? I'd make sure to keep all the current maintainers as admins...

My goal here is two fold:

* To promote this package a bit more (possibly making it part of the default ember-cli stack now that ember-template-lint is...)
* Increase the ease of collaboration between ember-template-lint and eslint-plugin-hbs

What do you think?

**Comment by psbanka** [comment]
yes, sorry this took so long to get back to you. I'd be happy to do this. Not sure exactly what is involved?

**Comment by rwjblue** [comment]
I think you can initiate a transfer to me (in the github settings, near the bottom) then it'll ask me to accept. Once its transferred I'll make sure to add you back as a maintainer/collaborator.

**Comment by psbanka** [comment]
Done! ✅

**Comment by psbanka** [comment]
@rwjblue — is there anything else left to be done here?

**Comment by rwjblue** [comment]
Hmm, I don't see the transfer request (probably got buried in my email or something 😩), sorry about that. 

Mind sending it again?

**Comment by psbanka** [comment]
@rwjblue Okay, initiated transfer again. LMK how it goes!

**Comment by rwjblue** [comment]
OK, looks like it worked, thank you!
